export const displayVariants = {
  display: {
    block: 'block',
    inline: 'inline',
    inlineBlock: 'inline-block',
    flex: 'flex',
    inlineFlex: 'inline-flex',
    grid: 'grid',
    inlineGrid: 'inline-grid',
  },
  'display:sm': {
    block: 'sm:block',
    inline: 'sm:inline',
    inlineBlock: 'sm:inline-block',
    flex: 'sm:flex',
    inlineFlex: 'sm:inline-flex',
    grid: 'sm:grid',
    inlineGrid: 'sm:inline-grid',
  },
  'display:md': {
    block: 'md:block',
    inline: 'md:inline',
    inlineBlock: 'md:inline-block',
    flex: 'md:flex',
    inlineFlex: 'md:inline-flex',
    grid: 'md:grid',
    inlineGrid: 'md:inline-grid',
  },
  'display:lg': {
    block: 'lg:block',
    inline: 'lg:inline',
    inlineBlock: 'lg:inline-block',
    flex: 'lg:flex',
    inlineFlex: 'lg:inline-flex',
    grid: 'lg:grid',
    inlineGrid: 'lg:inline-grid',
  },
};
