export const fontWeightVariants = {
  fontWeight: {
    thin: 'font-thin',
    extraLight: 'font-extralight',
    light: 'font-light',
    normal: 'font-normal',
    medium: 'font-medium',
    semiBold: 'font-semibold',
    bold: 'font-bold',
    extrabold: 'font-extrabold',
    black: 'font-black',
  },
  'fontWeight:sm': {
    thin: 'sm:font-thin',
    extraLight: 'sm:font-extralight',
    light: 'sm:font-light',
    normal: 'sm:font-normal',
    medium: 'sm:font-medium',
    semiBold: 'sm:font-semibold',
    bold: 'sm:font-bold',
    extrabold: 'sm:font-extrabold',
    black: 'sm:font-black',
  },
  'fontWeight:md': {
    thin: 'md:font-thin',
    extraLight: 'md:font-extralight',
    light: 'md:font-light',
    normal: 'md:font-normal',
    medium: 'md:font-medium',
    semiBold: 'md:font-semibold',
    bold: 'md:font-bold',
    extrabold: 'md:font-extrabold',
    black: 'md:font-black',
  },
  'fontWeight:lg': {
    thin: 'lg:font-thin',
    extraLight: 'lg:font-extralight',
    light: 'lg:font-light',
    normal: 'lg:font-normal',
    medium: 'lg:font-medium',
    semiBold: 'lg:font-semibold',
    bold: 'lg:font-bold',
    extrabold: 'lg:font-extrabold',
    black: 'lg:font-black',
  },
  'fontWeight:xl': {
    thin: 'xl:font-thin',
    extraLight: 'xl:font-extralight',
    light: 'xl:font-light',
    normal: 'xl:font-normal',
    medium: 'xl:font-medium',
    semiBold: 'xl:font-semibold',
    bold: 'xl:font-bold',
    extrabold: 'xl:font-extrabold',
    black: 'xl:font-black',
  },
};
