export const letterSpacingVariants = {
  letterSpacing: {
    tighter: 'tighter',
    tight: 'tight',
    normal: 'normal',
    wide: 'wide',
    wider: 'wider',
    widest: 'widest',
  },
  'letterSpacing:sm': {
    tighter: 'sm:tighter',
    tight: 'sm:tight',
    normal: 'sm:normal',
    wide: 'sm:wide',
    wider: 'sm:wider',
    widest: 'sm:widest',
  },
  'letterSpacing:md': {
    tighter: 'md:tighter',
    tight: 'md:tight',
    normal: 'md:normal',
    wide: 'md:wide',
    wider: 'md:wider',
    widest: 'md:widest',
  },
  'letterSpacing:lg': {
    tighter: 'lg:tighter',
    tight: 'lg:tight',
    normal: 'lg:normal',
    wide: 'lg:wide',
    wider: 'lg:wider',
    widest: 'lg:widest',
  },
  'letterSpacing:xl': {
    tighter: 'xl:tighter',
    tight: 'xl:tight',
    normal: 'xl:normal',
    wide: 'xl:wide',
    wider: 'xl:wider',
    widest: 'xl:widest',
  },
};
